MySite/MySite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySite/blog/urls.py
from django.urls import path
from .views import post_list, post_detail, PostListView, post_share, post_search
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         post_detail, name='post_detail'),
    #path('', PostListView.as_view(), name='post_list'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', post_search, name='post_search'),
]

MySite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class Post(models.Model):
    tags = TaggableManager()
    STATUS_CHOICES = [
        ('draft', 'Проект'),
        ('published', 'Опубликовано'),
    ]
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts', verbose_name='Автор')
    body = models.TextField(verbose_name='Основной текст поста')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='draft', verbose_name='Статус')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                        self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Комментарий {self.name} к посту {self.post}'

MySite/blog/forms.py
from django import forms
from django.forms import ModelForm

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

MySite/blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count


class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm(data=request.POST)
    if request.method == 'POST':
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        else:
            comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments,
                                                    'new_comment': new_comment,
                                                    'comment_form': comment_form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    form = EmailPostForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"Вам {cd['name']} ({cd['email']}), рекомендуют прочитать статью  {post.title}"
            message = f"{post.title} {post_url} {cd['name']} {cd['comments']}"
            send_mail(subject, message, 'jirotakeo@gmail.com', [cd['to']])
            sent = True
        else:
            form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        search_vector = SearchVector('body', weight='B') + SearchVector('title', weight='A')
        search_query = SearchQuery(query)
        results = Post.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.2).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

MySite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}
        <h2>{{ post.title }}</h2>
        <p class="date">Опубликовано: {{ post.publish }} Автор: {{ post.author }}</p>
            {{ post.body|markdown|linebreaks }}
        <p>
            <a href="{% url 'blog:post_share' post.id %}">Поделиться статьей</a>
        </p>
        {% with comments.count as total_comments %}
            <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
        {% endwith %}

        {% for comment in comments %}
            <div class="comment">
                <p class="info">{{ forloop.counter }} {{ comment.name }}</p>
                {{ comment.body|linebreaks }}
            </div>
        {% empty %}
            <p>Нет комментариев...</p>
        {% endfor %}

        {% if new_comments %}
            <h2>Комментарий добавлен</h2>
        {% else %}
            <h2>Оставьте комментарий</h2>
            <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Добавить"></p>
            </form>
        {% endif %}
        {% if similar_posts %}
            <p>Похожие статьи: </p>
<ul>
        {% for sp in similar_posts %}
            <li><a href="{{ sp.get_absolute_url }}">{{ sp }}</a></li>
        {% endfor %}
        {% endif %}
    </ul>
{% endblock %}

MySite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

MySite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %} Титул {% endblock %}
{% block content %}
    {% if tags %}
        <h2>{{ tag.name }}</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
            <p class="tags">Метки: {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
                        {% endfor %}
            </p>
            <p class="date">Опубликовано: {{ post.publish }} Автор: {{ post.author }}</p>
            {{ post.body|truncatewords_html:30|linebreaks }}
    {% endfor %}
{% include 'pagination.html' with page=posts %}
{% endblock %}

MySite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Пост  {{ query }}</h1>
        <h3>
            {% with results.count as total_results %}
                {{ total_results }} {{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            <p>{{ post.body|truncatewords:5 }}</p>
        {% empty %}
            <p>нет результата</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Искать заново</a></p>
        {% else %}
        <h1>Search for post</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

MySite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>Отправить на почту</h1>
        <p>"{{ post.title }}" успешно отправлено на {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Отправить статью "{{ post.title }}" на e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}